# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20180802_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
